### ISSUE TITLE
Замечания по программе замены подстрок в файле

### ISSUE THREAD

**Issue by alexey-malov** [Dzzirt/OOP#1]
``` c++
    if (argc != 5)
    {
        cout << "Need to input only 4 parameters" << endl;
    }
```

В случае, когда пользователь неправильно запустил программу, нужно вывести краткую инструкцию пользователя:
хотя бы так:

```
Usage:
replace.exe <input-file> <output-file> <search-string> <replace-string>
```

**Comment by alexey-malov** [comment]
```c++
const uintmax_t MAX_SIZE = 2147483648;
```
лучше добавить в конце числа суффикс UL,

**Comment by alexey-malov** [comment]
``` c++
 in.close();
```

входной файл можно явно не закрывать, т.к. при выходе из блока, в котором он объявлен, деструктор произведет закрытие

выходной файл закрывать явно имеет смысл (чтобы убедиться, что буферизированные данные записались на диск успешно), но предварительно настроив поток на выбрасывание исключений в случае ошибок (исключения рассматриваются в более поздних занятиях), либо вызвав flush и проверив результат:

``` c++
if (!strm.flush())
{
 // ошибка записи данных
}
```

**Comment by alexey-malov** [comment]
вынеси код из функции main в функцию вроде:
ReplaceStringInFile(inputFileName, outputFileName, searchstring, replaceString)
Это упростит код функции main

**Comment by Dzzirt** [comment]
Исправил

**Comment by alexey-malov** [comment]
``` c++
void ReplaceStringInFile(string inputFileName, string outputFileName, string search, string replace)
```

Строки, не меняющиеся внутри функции, следует передавать в функцию по константной ссылке, чтобы не выполнять их бессмысленное копирование

**Comment by alexey-malov** [comment]
Абсолютные пути к boost не нужно указывать в свойствах твоего проекта. На моем компе boost находится совсем в другом каталоге.
Воспользуйтся документом "Как установить boost и настроить Visual Studio для работы с ним.docx", который я тебе через вконтакте посылал.

**Comment by alexey-malov** [comment]
``` c++
void ReplaceStringInFile(string inputFileName, string outputFileName, string search, string replace)
```

Не ясно, как взывающая функция узнает о том былио ли ошибки в процессе работы. 
В результате функция main возвращает значение 0 (признак успешного завершения работы) вне зависимости от успешности выполнения своей работы

**Comment by alexey-malov** [comment]
Тесты должны проверять работу твоей программы в автоматическом режиме, т.е. твой батник должен прогнать программу с разными входными значениями, после каждого запуска сравнить результат ее работы (error code и то, что она вывела в выходные файлы и, возможно, в stdout) с ожидаемыми значениями. Под windows есть утилита fc, сравнивающая содержимое файлов. 

```
rem --Test Case 1. ----
rem Запускаем программу с некоторыми параметрами, перенаправляем вывод в stdout, а ввод осуществляем из testcase1\stdin
my_program.exe testcase1\input.txt output.txt <testcase1\stdin >stdout
if ERRORLEVEL 1 then goto error
rem сравниваем выходной файл программы с ожидаемым значением для данного теста
fc output.txt testcase1\expected_output.txt
if ERRORLEVEL 1 then goto error
rem сравниваем stdout программы с ожидаемым значением для данного теста
fc stdout test_case1\expected_stdout
if ERRORLEVEL 1 then goto error

rem --- Test Case 2 ---
rem аналогичным образом прогоняем программу на других входных данных
...

echo -- All tests succeeded --
exit /B

:error
echo some of the tests has failed
```

То есть ты не должен вручную проверять, что же программа вывела. Ты запускаешь скрипт и просто смотришь, вывела ли скрипт в конце OK или же сообщил о том, что какая-то из проверок провалилась.
Таким образом после внесения в программу изменений тебе не нужно вручную проверять ее работу на куче входных данных (это уныло и быстро тебе надоест), а просто прогоняешь тесты.
Если надо добавить какой-то новый функционал, то добавишь тест для следующей ситуации в скрипт (еще до реализации этого функционала в программе).

Почитай 0 лабораторную работу. Там это расписано

**Comment by alexey-malov** [comment]
За линейное время (или не хуже (N log N) можно решить задачу, если завести временную вторую строку-приемник
Воспользуйся методом reserve класса string для изменения вместимости строки-приемника
Для обмена содержимого временной строки и subject можно использовать метод swap (выполняется за константное время). Либо даже так: 
subject = move(buffer);
